{{- if and (not .Values.local) (not (not .Values.tls)) }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s" "letsencrypt" .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  {{ .Values.ingress.letsencrypt.email }}
    privateKeySecretRef:
      name: geppetto-meta-letsencrypt
    solvers:
    - http01:
        ingress:
          ingressName: geppetto-meta-ingress
{{ end }}
