language: node_js
sudo: required
node_js:
  - "9"

before_script:
  - npm install travis-ci

script:
  - npm i
  - ./node_modules/eslint/bin/eslint.js .
  - npm run test
  
after_success:
  - node travis/trigger-build.js