# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from volumetric_viewer.models.base_model_ import Model
from volumetric_viewer import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None):  # noqa: E501
        """InlineResponse2001 - a model defined in OpenAPI

        :param path: The path of this InlineResponse2001.  # noqa: E501
        :type path: str
        """
        self.openapi_types = {
            'path': str
        }

        self.attribute_map = {
            'path': 'path'
        }

        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self):
        """Gets the path of this InlineResponse2001.


        :return: The path of this InlineResponse2001.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this InlineResponse2001.


        :param path: The path of this InlineResponse2001.
        :type path: str
        """

        self._path = path
