# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from volumetric_viewer.models.base_model_ import Model
from volumetric_viewer import util


class InlineResponse500(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """InlineResponse500 - a model defined in OpenAPI

        :param error: The error of this InlineResponse500.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'error': str
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse500':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_500 of this InlineResponse500.  # noqa: E501
        :rtype: InlineResponse500
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this InlineResponse500.


        :return: The error of this InlineResponse500.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse500.


        :param error: The error of this InlineResponse500.
        :type error: str
        """

        self._error = error
