version: '1.0'
stages:
- prepare
- deploy
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  deployment:
    stage: deploy
    image: codefresh/cfstep-helm:3.4.1
    title: Installing chart
    environment:
    - CHART_REF=./deployment/helm
    - RELEASE_NAME=${{NAMESPACE}}
    - KUBE_CONTEXT=${{CLUSTER_NAME}}
    - NAMESPACE=${{NAMESPACE}}
    - CHART_VERSION=${{DEPLOYMENT_TAG}}
    - HELM_REPO_USE_HTTP=false
    - HELM_REPO_CONTEXT_PATH=
    - TIMEOUT=600s
    - VALUESFILE_values=./deployment/helm/values.yaml
  approval:
    type: pending-approval
    stage: publish
    title: Approve
    description: Approve publication
    timeout:
      duration: 168
      finalState: approved
  git-tag:
    title: Performing git tagging
    stage: publish
    image: alpine/git:latest
    commands:
    - git tag ${{DEPLOYMENT_PUBLISH_TAG}}
    - ORIGIN=$(git remote get-url origin)
    - PROTOCOL=https://
    - REPLACEMENT=${PROTOCOL}${{REPO_TOKEN}}@
    - git remote set-url origin ${ORIGIN/$PROTOCOL/$REPLACEMENT}
    - git push origin --tags
    when:
      condition:
        all:
          whenVarExists: includes("${{DEPLOYMENT_PUBLISH_TAG}}", "{{DEPLOYMENT_PUBLISH_TAG}}")
            == false
          whenVarExists2: includes("${{REPO_TOKEN}}", "{{REPO_TOKEN}}") == false
