---
root: true
extends:
  - eslint:recommended
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - plugin:react/recommended

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - jest
  - react
  - react-hooks
  - "@typescript-eslint/eslint-plugin"
settings:
  react:
    version: detect
env:
  jest/globals: true
  browser: true
  es6: true
rules:
  no-console: 0
  func-style: 0
  consistent-return: 2
  prefer-arrow-callback:
    - 2
    - allowNamedFunctions: true
      allowUnboundThis: false
  jest/no-disabled-tests: 2
  jest/no-focused-tests: 2
  react/prop-types: 0
  react/forbid-prop-types: 0
  react/no-unused-prop-types: 0
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  curly: 2
  no-tabs: 2
  arrow-spacing: 2
  no-unneeded-ternary: 2
  object-curly-spacing:
    - 2
    - always
  indent:
    - 2
    - 2
    - SwitchCase: 1
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/ban-ts-comment": 0

globals:
  __dirname: writable
  module: writable
