// Bogus actions for development
export const SELECT_INSTANCE = "SELECT_INSTANCE";
export const LOAD_MODEL = "LOAD_MODEL";
export const MODEL_LOADING = "MODEL_LOADING";
export const MODEL_LOADED = "MODEL_LOADED";

// Client actions
export const SELECT = "SELECTION_CHANGED";
export const VISIBILITY_CHANGED = "VISIBILITY_CHANGED";
export const FOCUS_CHANGED = "FOCUS_CHANGED";
export const EXPERIMENT_OVER = "EXPERIMENT_OVER";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const PROJECT_LOADED = "PROJECT_LOADED";
export const PROJECT_DOWNLOADED = "PROJECT_DOWNLOADED";
// export const MODEL_LOADED = "MODEL_LOADED";
export const EXPERIMENT_LOADED = "EXPERIMENT_LOADED";
export const MODELTREE_POPULATED = "MODELTREE_POPULATED";
export const SIMULATIONTREE_POPULATED = "SIMULATIONTREE_POPULATED";
export const DO_EXPERIMENT_PLAY = "DO_EXPERIMENT_PLAY";
export const EXPERIMENT_PLAY = "EXPERIMENT_PLAY";
export const EXPERIMENT_STATUS_CHECK = "EXPERIMENT_STATUS_CHECK";
export const EXPERIMENT_PAUSE = "EXPERIMENT_PAUSE";
export const EXPERIMENT_RESUME = "EXPERIMENT_RESUME";
export const EXPERIMENT_RUNNING = "EXPERIMENT_RUNNING";
export const EXPERIMENT_STOP = "EXPERIMENT_STOP";
export const EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED";
export const EXPERIMENT_FAILED = "EXPERIMENT_FAILED";
export const EXPERIMENT_UPDATE = "EXPERIMENT_UPDATE";
export const EXPERIMENT_UPDATED = "EXPERIMENT_UPDATED";
export const EXPERIMENT_RENAMED = "EXPERIMENT_RENAMED";
export const EXPERIMENT_DELETED = "EXPERIMENT_DELETED";
export const EXPERIMENT_ACTIVE = "EXPERIMENT_ACTIVE";
export const EXPERIMENT_CREATED = "EXPERIMENT_CREATED";
export const PROJECT_PERSISTED = "PROJECT_PERSISTED";
export const SPOTLIGHT_CLOSED = "SPOTLIGHT_CLOSED";
export const SPOTLIGHT_LOADED = "SPOTLIGHT_LOADED";
export const INSTANCE_DELETED = "INSTANCE_DELETED";
export const INSTANCES_CREATED = "INSTANCES_CREATED";
export const SHOW_TUTORIAL = "SHOW_TUTORIAL";
export const HIDE_TUTORIAL = "HIDE_TUTORIAL";
export const SHOW_SPINNER = "SHOW_SPINNER";
export const HIDE_SPINNER = "HIDE_SPINNER";
export const COLOR_SET = "COLOR_SET";
export const CANVAS_INITIALISED = "CANVAS_INITIALISED";
export const PROJECT_MADE_PUBLIC = "PROJECT_MADE_PUBLIC";
export const CONTROL_PANEL_OPEN = "CONTROL_PANEL_OPEN";
export const CONTROL_PANEL_CLOSE = "CONTROL_PANEL_CLOSE";
export const LIT_ENTITIES_CHANGED = "LIT_ENTITIES_CHANGED";
export const COMPONENT_DESTROYED = "COMPONENT_DESTROYED";
export const EXPERIMENT_PROPERTIES_SAVED = "EXPERIMENT_PROPERTIES_SAVED";
export const PROJECT_PROPERTIES_SAVED = "PROJECT_PROPERTIES_SAVED";
export const PARAMETERS_SET = "PARAMETERS_SET";
export const COMMAND_LOG = "COMMAND_LOG";
export const COMMAND_LOG_DEBUG = "COMMAND_LOG_DEBUG";
export const COMMAND_LOG_RUN = "COMMAND_LOG_RUN";
export const COMMAND_CLEAR = "COMMAND_CLEAR";
export const COMMAND_TOGGLE_IMPLICIT = "COMMAND_TOGGLE_IMPLICIT";
export const RECEIVE_PYTHON_MESSAGE = "RECEIVE_PYTHON_MESSAGE";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const ERROR_WHILE_EXEC_PYTHON_COMMAND = "ERROR_WHILE_EXEC_PYTHON_COMMAND";

// Model actions

export const selectInstance = ( scope, geometryIdentifier, point ) => ({
  type: SELECT_INSTANCE,
  data: {
    scope: scope,
    geometryIdentifier: geometryIdentifier,
    point: point
  }
});
