name: Geppetto.js Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: geppetto.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x, 22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          (cd geppetto-core && yarn && yarn test)
          (cd geppetto-ui && yarn && yarn test)
          (cd geppetto-client && yarn && yarn test)
